greeting:
  message: This is Spring config BUS TEST 

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 1234
# spring:
#   rabbitmq:
#     host: 127.0.0.1
#     port: 5672
#     username: guest
#     password: {cipher}382cd267bd1a1fa4ddcbf6ecb1ef7afdaf6e8e3be90187ab3db5e75aac120b3b