server:
  port: 8888

spring:
  application:
    name: config-service
#  profiles:
#    active: native
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
#        native:
#          search-locations: file:///d/source/Spring_pratice/git-local-repo/ecommerce.yml
        git:
          uri: https://github.com/Seeongh/spring-proejct/tree/4938bd621e8ceae7fa47980974f28c843fb7d3a4/git-local-repo
          default-Label: master

management:
  endpoints:
    web:
      exposure:
        include: health, bus-refresh
